games = [
    "Music Vol 1 by Daniel Bienvenu (2000) (PD).col",
    "Tutankham (1983) (Parker Bros).col",
    "Amazing Snake Beta X by Serge-Eric Tremblay (2001) (PD).col",
    "BC's Quest for Tires (1983) (Sierravision) [a1].col",
    "Amazing Bumpman (1986) (Telegames).col",
    "Tic Tac Toe by Norman Nithman (1996) (PD) [a1].col",
    "Artillery Duel (1983) (Xonox).col",
    "James Bond 007 (1984) (Parker Bros).col",
    "Purple Dinosaur Massacre by John Dondzila (1996) (PD).col",
    "Looping (1983) (Venture Line).col",
    "Star Trek - Strategic Operations Simulator (1984) (Sega).col",
    "St-Valentine's Day (2002) (PD).col",
    "Boulder Dash (1984) (Telegames) [t2] (9 Men).col",
    "Heist, The (1983) (Micro Fun).col",
    "Strike It! (1983) (Telegames) [!].col",
    "Sewer Sam (1984) (Interphase).col",
    "Puckman Sounds V002 (2003) (PD).col",
    "Super Action Football (1984) (Coleco).col",
    "Ken Uston's Blackjack-Poker (1983).col",
    "Space Panic (1983) (Universal).col",
    "Fortune Builder (1984) (Circuits and Systems).col",
    "Linking Logic (1984) (Fisher-Price).col",
    "Meteoric Shower (1983) (Bit Corp).col",
    "Pitstop (1983) (Epyx) [a1].col",
    "Wizard of Id's Wizmath (1984) (Sierravision).col",
    "Sound FX Vol 2 by Daniel Bienvenu (2000) (PD).col",
    "Dacman (Jul 29) by Daniel Bienvenu (2000) (PD).col",
    "Cabbage Patch Kids - Adventures in the Park (1983) (Proto).col",
    "Boulder Dash (1984) (Telegames) [t1] (50 Men).col",
    "Super Action Soccer (1984) (Coleco).col",
    "Robin Hood (1984) (Xonox) [a1].col",
    "BUsTin-Out Volume 2 by Daniel Bienvenu (2000) (PD).col",
    "Gateway to Apshai (1984) (Epyx).col",
    "Frenzy! (1982-83) [a1].col",
    "Cosmo Fighter 3 Demo by Marcel de Kogel (2001) (PD).col",
    "Space Invasion by John Dondzila (1998) (PD).col",
    "Aquattack (1984) (Interphase) [a1].col",
    "Dacman (Jul 16) by Daniel Bienvenu (2000) (PD).col",
    "Burgertime (1982-84) (Data East).col",
    "Breakout by Daniel Bienvenu (Feb 02) (1999) (PD).col",
    "Nim by Daniel Bienvenu (Nov 03) (2000) (PD).col",
    "Squish 'Em Sam! (1983) (Interphase).col",
    "Dacman (Jul 28) by Daniel Bienvenu (2000) (PD).col",
    "Puckman Sounds V003 (2003) (PD).col",
    "Pitstop (1983) (Epyx).col",
    "Dig Dug (1983) (Atarisoft) (Prototype).col",
    "Sector Alpha (1983) (Spectravideo).col",
    "Moonsweeper (1983) (Imagic).col",
    "Bump 'N' Jump (1982-84) (Data East).col",
    "Air Battle V0.4 by Daniel Bienvenu (July 10) (2000) (PD).col",
    "Pepper II (1983) (Exidy).col",
    "Congo Bongo (1984).col",
    "Star Wars - The Arcade Game (1984) (Parker Bros).col",
    "Nova Blast (1983) (Imagic) [a1][!].col",
    "Chateau du Dragon, Le by Daniel Bienvenu (2001) (PD).col",
    "Jungle Hunt (1983) (Atarisoft).col",
    "Matt Patrol (1984) (Atarisoft) (Prototype).col",
    "Wing War (1983) (Imagic).col",
    "Its Only Rock 'N' Roll (1984) (Xonox).col",
    "Monkey Academy (1984) (Konami) (Prototype).col",
    "Logic Levels (1984) (Fisher-Price).col",
    "Popeye (1983) (Parker Bros) [a1].col",
    "Puckman Sounds V001 (2003) (PD).col",
    "DragonFire (1984) (Imagic).col",
    "Fathom (1983) (Imagic).col",
    "Subroc (1983) (Sega) [a1].col",
    "Facemaker (1983) (Spinnaker) [!].col",
    "Jumpman Junior (1984) (Epyx).col",
    "Keystone Kapers (1983-84) (Activision).col",
    "Frontline (1983) (Taito) [a1].col",
    "Frogger II - ThreeDeep! (1984) (Parker Bros).col",
    "Galaxian (1983) (Atarisoft) [a3].col",
    "Tunnels & Trolls Demo (1983) (Adam).col",
    "Q-bert (1983) (Parker Bros) [a1].col",
    "Antarctic Adventure (1984) (Konami).col",
    "Dacman (Aug 16) by Daniel Bienvenu (2000) (PD).col",
    "Brain Strainers (1984) (Carousel).col",
    "St-Valentine's Day (No Alien Head) (2002) (PD).col",
    "Killer Instinct by Daniel Bienvenu (1997) (PD).col",
    "Mousetrap (1982) (Exidy).col",
    "Heist, The (1983) (Micro Fun) [t1] (50 Men).col",
    "Motocross Racer (1984) (Xonox) [a1].col",
    "Adam's Musicbox Demo (1987) (Coleco).col",
    "Oil's Well (1984) (Sierravision).col",
    "Gorf (1981-83) (Midway).col",
    "Boulder Dash (1984) (Micro Fun).col",
    "BC's Quest for Tires II - Grog's Revenge (1984) (32k).col",
    "Kill Barney in Tokyo by Daniel Bienvenu (1997) (PD).col",
    "Rock 'N' Bolt (1984) (Telegames) [a1].col",
    "Tarzan (1984) (Coleco).col",
    "Popeye (1983) (Parker Bros).col",
    "Robin Hood (1984) (Xonox).col",
    "Miner 2049er (1983) (Micro Fun) [t1] (50 Men).col",
    "Final Test Cartridge (19xx).col",
    "Donkey Kong Jr (1982-83).col",
    "Winky Trap by John Dondzila (1997) (PD).col",
    "Super Action Football (1984) (Coleco) [a1].col",
    "Demon2 Demo by Yannick Proulx (2001) (PD).col",
    "Q-bert II (1984) (Parker Bros).col",
    "Spectron (1983) (Spectravideo).col",
    "Mountain King (1983-84) (Sunrise) [!].col",
    "Pere Noel by Daniel Bienvenu (2000) (PD).col",
    "Kevtris by Kevin Horton (1996) (PD) [a1].col",
    "Galaxian (1983) (Atarisoft) [a1].col",
    "Rolloverture (1983) (Sunrise).col",
    "Bejeweled Demo by Daniel Bienvenu (2001) (PD).col",
    "Dacman (Jul 22) by Daniel Bienvenu (2000) (PD).col",
    "Joust (1983) (Atarisoft) (Prototype).col",
    "Cosmo Challenge-Trainer Menu by Marcel de Kogel (1997) (PD).col",
    "BUsTin-Out Volume 3 by Daniel Bienvenu (2000) (PD).col",
    "Montezuma's Revenge (1984) (Parker Bros).col",
    "Buck Rogers - Planet of Zoom (1983) (Sega) [a1].col",
    "H.E.R.O. (1984) (Activision).col",
    "Zaxxon (1982) (Sega).col",
    "War Room (1983) (Probe 2000).col",
    "Heist, The (1983) (Micro Fun) [a1].col",
    "Gyruss (1984) (Parker Bros).col",
    "Threshold (1983) (Sierravision).col",
    "Illusions (1984) (Nice Ideas).col",
    "Subroc (1983) (Sega).col",
    "Superpong Demo (2000) (PD).col",
    "Gust Buster (1983) (Sunrise).col",
    "Dam Busters, The (1984).col",
    "Telly Turtle (1984) (Carousel).col",
    "BUsTin-Out Demo 0.5 by Daniel Bienvenu (2000) (PD).col",
    "Venture (1982) (Exidy).col",
    "Super Cobra (1983) (Parker Bros).col",
    "ColRen.rar",
    "Video Hustler (1984) (Konami) (Prototype).col",
    "Pac-Man (1983) (Atarisoft) (Prototype).col",
    "Flipper Slipper (1983) (Spectravideo).col",
    "Dance Fantasy (1984) (Fisher-Price).col",
    "Porky's (1983) (20th Century Fox) (Prototype).col",
    "Miner 2049er (1983) (Micro Fun).col",
    "Quest for Quintana Roo (1983) (Sunrise) [a1].col",
    "Turbo (1982) (Sega).col",
    "War Room (1983) (Probe 2000) [a1].col",
    "Chuck Norris - Super Kicks (1983) (Xonox).col",
    "Breakout Paddle Demo by Daniel Bienvenu (Feb 12) (2001) (PD).col",
    "One on One Basketball (1984) (Micro Fun).col",
    "Dacman (Aug 08) by Daniel Bienvenu (2000) (PD).col",
    "Tic Tac Toe by Norman Nithman (1996) (PD).col",
    "Tenchi Muyo Demo by Daniel Bienvenu (2000) (PD).col",
    "River Raid (1982-84) (Activision) [!].col",
    "Super Cross Force (1983) (Spectravideo) [a1].col",
    "Ms. Space Fury (Digital Press) (2001).col",
    "Spy Hunter (1983-84) (Midway).col",
    "Juke Box (1984) (Spinnaker).col",
    "Steamroller (1984) (Activision) (Prototype).col",
    "Heist, The (1983) (Micro Fun) [t2] (8 Men).col",
    "Motocross Racer (1984) (Xonox).col",
    "Cabbage Patch Kids - Adventure in the Park (1983).col",
    "Tank Wars (1983) (Bit Corp) [!].col",
    "Victory (1983).col",
    "Yolk's on You, The (1983) (20th Century Fox) (Prototype).col",
    "Sector Alpha (1983) (Spectravideo) [a2].col",
    "Cosmo Fighter 2 by Marcel de Kogel (1996-97) (PD).col",
    "Dukes of Hazzard, The (1984) (Warner Bros).col",
    "Star Fortress by John Dondzila (1997) (PD).col",
    "Fall Guy (1983) (20th Century Fox) (Prototype).col",
    "Escape From The Mind Master (1983) (Starpath) (Prototype).col",
    "Tomarc the Barbarian (1984) (Xonox).col",
    "Dacman (Jul 18) by Daniel Bienvenu (2000) (PD).col",
    "Campaign '84 (1983) (Sunrise).col",
    "M.A.S.H. (1983) (20th Century Fox) (Prototype).col",
    "Blockade Runner (1984) (Interphase).col",
    "Pitfall! (1983) (Activision) [!].col",
    "Cosmo Challenge by Marcel de Kogel (1997) (PD).col",
    "Destructor (1984) (Coleco).col",
    "Tapper (1984) (Midway).col",
    "Space Invaders Collection Pack Demo (2002) (PD).col",
    "Stubby Demo by Yannick Proulx (2001) (PD).col",
    "Cosmic Avenger (1982) (Universal).col",
    "Sector Alpha (1983) (Spectravideo) [a1].col",
    "Centipede (1983) (Atarisoft).col",
    "Time Pilot (1983) (Konami).col",
    "War Games (1983-84).col",
    "Lady Bug (1982) (Universal).col",
    "Power Lords - Quest for Volcan (1983) (Prototype).col",
    "Dacman (Aug 01) by Daniel Bienvenu (2000) (PD).col",
    "Jumpman Junior (1984) (Epyx) [a1].col",
    "Super Cross Force (1983) (Spectravideo).col",
    "generategamelist.py",
    "Evolution (1983) (Sydney).col",
    "Sir Lancelot (1983) (Xonox) [!].col",
    "Learning With Leeper (1983) (Sierravision) [!].col",
    "Super Action Baseball (1983) (Coleco).col",
    "Pitstop (1983) (Epyx) [a2].col",
    "Mr. Do's Castle (1983) (Parker Bros).col",
    "Cosmic Crisis (1983) (Bit Corp).col",
    "Space Fury (1983) (Sega).col",
    "Christmas Demo by Daniel Bienvenu (Dec 25) (2001) (PD).col",
    "Miner 2049er (1983) (Micro Fun) [a1].col",
    "Dr. Seuss's Fix-Up The Mix-Up Puzzler (1984) (Coleco).col",
    "Q-bert (1983) (Parker Bros).col",
    "Monkey Academy (1984) (Konami).col",
    "Mr. Do! (1983) (Universal).col",
    "Super DK! Junior (1983) (Prototype).col",
    "Omega Race (1981-83) (Midway).col",
    "Bump 'N' Jump (1982-84) (Mattel) (Prototype).col",
    "Slurpy (1984) (Xonox).col",
    "Frenzy! (1982-83).col",
    "Donkey Kong (1982).col",
    "Super DK! (1983) (Prototype).col",
    "Miner 2049er (1983) (Micro Fun) [t2] (8 Men).col",
    "Super Cobra (1983) (Parker Bros) [a1].col",
    "Smurf - Paint 'n Play Workshop (1983).col",
    "Mountain King (1983-84) (Sunrise) [a1].col",
    "Amazing Snake Beta 5 by Serge-Eric Tremblay (2001) (PD).col",
    "Quest for Quintana Roo (1983) (Sunrise) [!].col",
    "Frontline (1983) (Taito).col",
    "Aquattack (1984) (Interphase).col",
    "Sammy Lightfoot (1983) (Sierravision).col",
    "Space Invasion Demo by John Dondzila (Feb 06) (1998) (PD).col",
    "Up 'N Down (1984) (Sega).col",
    "Happy Halloween by Daniel Bienvenu (2001) (PD).col",
    "Frogger (1982-83) (Parker Bros).col",
    "Burgertime (1982-83) (Mattel) (Prototype).col",
    "Carnival (1982).col",
    "Fraction Fever (1983) (Spinnaker).col",
    "Skiing (1986) (Telegames).col",
    "Word Feud (1984) (Xonox).col",
    "Spectank Demo by Daniel Bienvenu (2000) (PD).col",
    "Galaxian (1983) (Atarisoft).col",
    "Nova Blast (1983) (Imagic) [!].col",
    "Defender (1983) (Atarisoft).col",
    "BUsTin-Out Volume 1 by Daniel Bienvenu (2000) (PD).col",
    "Alphabet Zoo (1984) (Spinnaker).col",
    "Sound FX Vol 1 by Daniel Bienvenu (2000) (PD).col",
    "Cosmic Avenger (1982) (Universal) [a1].col",
    "Cosmo Trainer by Marcel de Kogel (1997) (PD).col",
    "Moonsweeper (1983) (Imagic) [a1].col",
    "BC's Quest for Tires II - Grog's Revenge (1984) (24k) [a1].col",
    "Sammy Lightfoot (1983) (Sierravision) [a1].col",
    "Super Action Baseball (1983) (Coleco) [a1].col",
    "Dacman (Jul 19) by Daniel Bienvenu (2000) (PD).col",
    "Frantic Freddy (1983) (Spectravideo).col",
    "Cabbage Patch Kids Picture Show (1984).col",
    "Carnival (1982) [a1].col",
    "Dacman (Jul 17) by Daniel Bienvenu (2000) (PD).col",
    "Galaxian (1983) (Atarisoft) [a2].col",
    "Slither (1983) (Century II).col",
    "BUsTin-Out Volume 0 by Daniel Bienvenu (2000) (PD).col",
    "Donkey Kong for Adam (1982).col",
    "Amazing Snake Beta 4 by Serge-Eric Tremblay (2001) (PD).col",
    "Mr. Do! (1983) (Universal) [a1].col",
    "Pitfall II - Lost Caverns (1983-84) (Activision).col",
    "Adventurium3 Demo (2000) (PD).col",
    "Antarctic Adventure (1984) (Konami) (Prototype).col",
    "Beamrider (1983) (Activision) [!].col",
    "Rocky Super-Action Boxing (1983) (Coleco).col",
    "Tournament Tennis (1984) (Imagic) [!].col",
    "Smurf - Rescue in Gargamel's Castle (1982).col",
    "Stubby Demo by Yannick Proulx (2001) (PD) [a1].col",
    "Alcazar - The Forgotten Fortress (1985) (Activision).col",
    "2010 - The Graphic Action Game (1984) (Coleco).col",
    "ColecoVision Noise Generator by Marcel de Kogel (1996) (PD).col",
    "Reversi Demo by Daniel Bienvenu (2001) (PD).col",
    "Zenji (1984) (Activision).col",
    "Choplifter (1982-84) (Broderbund).col",
    "Rock 'N' Bolt (1984) (Telegames).col",
    "Dacman (Jul 12) by Daniel Bienvenu (2000) (PD).col",
    "Kevtris by Kevin Horton (1996) (PD).col",
    "ColecoVision BIOS (1982).col",
    "Decathlon (1983) (Activision).col",
    "ColecoVision Monitor Test (1982).col",
    "BC's Quest for Tires (1983) (Sierravision).col",
    "Super Action Controller Test Cartridge (1983) (Nuvatec).col",
    "Memory Manor (1984) (Fisher-Price).col",
    "Buck Rogers - Planet of Zoom (1983) (Sega).col",
    "Roc 'N Rope (1983-84) (Konami).col"
];
