games = [
    ["2010 - The Graphic Action Game (1984) (Coleco).col", "colecovision"],
    ["Adam's Musicbox Demo (1987) (Coleco).col", "colecovision"],
    ["Adventurium3 Demo (2000) (PD).col", "colecovision"],
    ["Air Battle V0.4 by Daniel Bienvenu (July 10) (2000) (PD).col", "colecovision"],
    ["Alcazar - The Forgotten Fortress (1985) (Activision).col", "colecovision"],
    ["Alphabet Zoo (1984) (Spinnaker).col", "colecovision"],
    ["Amazing Bumpman (1986) (Telegames).col", "colecovision"],
    ["Amazing Snake Beta 4 by Serge-Eric Tremblay (2001) (PD).col", "colecovision"],
    ["Amazing Snake Beta 5 by Serge-Eric Tremblay (2001) (PD).col", "colecovision"],
    ["Amazing Snake Beta X by Serge-Eric Tremblay (2001) (PD).col", "colecovision"],
    ["Antarctic Adventure (1984) (Konami) (Prototype).col", "colecovision"],
    ["Antarctic Adventure (1984) (Konami).col", "colecovision"],
    ["Aquattack (1984) (Interphase) [a1].col", "colecovision"],
    ["Aquattack (1984) (Interphase).col", "colecovision"],
    ["Artillery Duel (1983) (Xonox).col", "colecovision"],
    ["BC's Quest for Tires (1983) (Sierravision) [a1].col", "colecovision"],
    ["BC's Quest for Tires (1983) (Sierravision).col", "colecovision"],
    ["BC's Quest for Tires II - Grog's Revenge (1984) (24k) [a1].col", "colecovision"],
    ["BC's Quest for Tires II - Grog's Revenge (1984) (32k).col", "colecovision"],
    ["BUsTin-Out Demo 0.5 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["BUsTin-Out Volume 0 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["BUsTin-Out Volume 1 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["BUsTin-Out Volume 2 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["BUsTin-Out Volume 3 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Beamrider (1983) (Activision) [!].col", "colecovision"],
    ["Bejeweled Demo by Daniel Bienvenu (2001) (PD).col", "colecovision"],
    ["Blockade Runner (1984) (Interphase).col", "colecovision"],
    ["Boulder Dash (1984) (Micro Fun).col", "colecovision"],
    ["Boulder Dash (1984) (Telegames) [t1] (50 Men).col", "colecovision"],
    ["Boulder Dash (1984) (Telegames) [t2] (9 Men).col", "colecovision"],
    ["Brain Strainers (1984) (Carousel).col", "colecovision"],
    ["Breakout Paddle Demo by Daniel Bienvenu (Feb 12) (2001) (PD).col", "colecovision"],
    ["Breakout by Daniel Bienvenu (Feb 02) (1999) (PD).col", "colecovision"],
    ["Buck Rogers - Planet of Zoom (1983) (Sega) [a1].col", "colecovision"],
    ["Buck Rogers - Planet of Zoom (1983) (Sega).col", "colecovision"],
    ["Bump 'N' Jump (1982-84) (Data East).col", "colecovision"],
    ["Bump 'N' Jump (1982-84) (Mattel) (Prototype).col", "colecovision"],
    ["Burgertime (1982-83) (Mattel) (Prototype).col", "colecovision"],
    ["Burgertime (1982-84) (Data East).col", "colecovision"],
    ["Cabbage Patch Kids - Adventure in the Park (1983).col", "colecovision"],
    ["Cabbage Patch Kids - Adventures in the Park (1983) (Proto).col", "colecovision"],
    ["Cabbage Patch Kids Picture Show (1984).col", "colecovision"],
    ["Campaign '84 (1983) (Sunrise).col", "colecovision"],
    ["Carnival (1982) [a1].col", "colecovision"],
    ["Carnival (1982).col", "colecovision"],
    ["Centipede (1983) (Atarisoft).col", "colecovision"],
    ["Chateau du Dragon, Le by Daniel Bienvenu (2001) (PD).col", "colecovision"],
    ["Choplifter (1982-84) (Broderbund).col", "colecovision"],
    ["Christmas Demo by Daniel Bienvenu (Dec 25) (2001) (PD).col", "colecovision"],
    ["Chuck Norris - Super Kicks (1983) (Xonox).col", "colecovision"],
    ["ColRen.rar", "colecovision"],
    ["ColecoVision BIOS (1982).col", "colecovision"],
    ["ColecoVision Monitor Test (1982).col", "colecovision"],
    ["ColecoVision Noise Generator by Marcel de Kogel (1996) (PD).col", "colecovision"],
    ["Congo Bongo (1984).col", "colecovision"],
    ["Cosmic Avenger (1982) (Universal) [a1].col", "colecovision"],
    ["Cosmic Avenger (1982) (Universal).col", "colecovision"],
    ["Cosmic Crisis (1983) (Bit Corp).col", "colecovision"],
    ["Cosmo Challenge by Marcel de Kogel (1997) (PD).col", "colecovision"],
    ["Cosmo Challenge-Trainer Menu by Marcel de Kogel (1997) (PD).col", "colecovision"],
    ["Cosmo Fighter 2 by Marcel de Kogel (1996-97) (PD).col", "colecovision"],
    ["Cosmo Fighter 3 Demo by Marcel de Kogel (2001) (PD).col", "colecovision"],
    ["Cosmo Trainer by Marcel de Kogel (1997) (PD).col", "colecovision"],
    ["Dacman (Aug 01) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Aug 08) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Aug 16) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 12) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 16) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 17) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 18) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 19) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 22) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 28) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dacman (Jul 29) by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Dam Busters, The (1984).col", "colecovision"],
    ["Dance Fantasy (1984) (Fisher-Price).col", "colecovision"],
    ["Decathlon (1983) (Activision).col", "colecovision"],
    ["Defender (1983) (Atarisoft).col", "colecovision"],
    ["Demon2 Demo by Yannick Proulx (2001) (PD).col", "colecovision"],
    ["Destructor (1984) (Coleco).col", "colecovision"],
    ["Dig Dug (1983) (Atarisoft) (Prototype).col", "colecovision"],
    ["Donkey Kong (1982).col", "colecovision"],
    ["Donkey Kong Jr (1982-83).col", "colecovision"],
    ["Donkey Kong for Adam (1982).col", "colecovision"],
    ["Dr. Seuss's Fix-Up The Mix-Up Puzzler (1984) (Coleco).col", "colecovision"],
    ["DragonFire (1984) (Imagic).col", "colecovision"],
    ["Dukes of Hazzard, The (1984) (Warner Bros).col", "colecovision"],
    ["Escape From The Mind Master (1983) (Starpath) (Prototype).col", "colecovision"],
    ["Evolution (1983) (Sydney).col", "colecovision"],
    ["Facemaker (1983) (Spinnaker) [!].col", "colecovision"],
    ["Fall Guy (1983) (20th Century Fox) (Prototype).col", "colecovision"],
    ["Fathom (1983) (Imagic).col", "colecovision"],
    ["Final Test Cartridge (19xx).col", "colecovision"],
    ["Flipper Slipper (1983) (Spectravideo).col", "colecovision"],
    ["Fortune Builder (1984) (Circuits and Systems).col", "colecovision"],
    ["Fraction Fever (1983) (Spinnaker).col", "colecovision"],
    ["Frantic Freddy (1983) (Spectravideo).col", "colecovision"],
    ["Frenzy! (1982-83) [a1].col", "colecovision"],
    ["Frenzy! (1982-83).col", "colecovision"],
    ["Frogger (1982-83) (Parker Bros).col", "colecovision"],
    ["Frogger II - ThreeDeep! (1984) (Parker Bros).col", "colecovision"],
    ["Frontline (1983) (Taito) [a1].col", "colecovision"],
    ["Frontline (1983) (Taito).col", "colecovision"],
    ["Galaxian (1983) (Atarisoft) [a1].col", "colecovision"],
    ["Galaxian (1983) (Atarisoft) [a2].col", "colecovision"],
    ["Galaxian (1983) (Atarisoft) [a3].col", "colecovision"],
    ["Galaxian (1983) (Atarisoft).col", "colecovision"],
    ["Gateway to Apshai (1984) (Epyx).col", "colecovision"],
    ["Gorf (1981-83) (Midway).col", "colecovision"],
    ["Gust Buster (1983) (Sunrise).col", "colecovision"],
    ["Gyruss (1984) (Parker Bros).col", "colecovision"],
    ["H.E.R.O. (1984) (Activision).col", "colecovision"],
    ["Happy Halloween by Daniel Bienvenu (2001) (PD).col", "colecovision"],
    ["Heist, The (1983) (Micro Fun) [a1].col", "colecovision"],
    ["Heist, The (1983) (Micro Fun) [t1] (50 Men).col", "colecovision"],
    ["Heist, The (1983) (Micro Fun) [t2] (8 Men).col", "colecovision"],
    ["Heist, The (1983) (Micro Fun).col", "colecovision"],
    ["Illusions (1984) (Nice Ideas).col", "colecovision"],
    ["Its Only Rock 'N' Roll (1984) (Xonox).col", "colecovision"],
    ["James Bond 007 (1984) (Parker Bros).col", "colecovision"],
    ["Joust (1983) (Atarisoft) (Prototype).col", "colecovision"],
    ["Juke Box (1984) (Spinnaker).col", "colecovision"],
    ["Jumpman Junior (1984) (Epyx) [a1].col", "colecovision"],
    ["Jumpman Junior (1984) (Epyx).col", "colecovision"],
    ["Jungle Hunt (1983) (Atarisoft).col", "colecovision"],
    ["Ken Uston's Blackjack-Poker (1983).col", "colecovision"],
    ["Kevtris by Kevin Horton (1996) (PD) [a1].col", "colecovision"],
    ["Kevtris by Kevin Horton (1996) (PD).col", "colecovision"],
    ["Keystone Kapers (1983-84) (Activision).col", "colecovision"],
    ["Kill Barney in Tokyo by Daniel Bienvenu (1997) (PD).col", "colecovision"],
    ["Killer Instinct by Daniel Bienvenu (1997) (PD).col", "colecovision"],
    ["Lady Bug (1982) (Universal).col", "colecovision"],
    ["Learning With Leeper (1983) (Sierravision) [!].col", "colecovision"],
    ["Linking Logic (1984) (Fisher-Price).col", "colecovision"],
    ["Logic Levels (1984) (Fisher-Price).col", "colecovision"],
    ["Looping (1983) (Venture Line).col", "colecovision"],
    ["M.A.S.H. (1983) (20th Century Fox) (Prototype).col", "colecovision"],
    ["Matt Patrol (1984) (Atarisoft) (Prototype).col", "colecovision"],
    ["Memory Manor (1984) (Fisher-Price).col", "colecovision"],
    ["Meteoric Shower (1983) (Bit Corp).col", "colecovision"],
    ["Miner 2049er (1983) (Micro Fun) [a1].col", "colecovision"],
    ["Miner 2049er (1983) (Micro Fun) [t1] (50 Men).col", "colecovision"],
    ["Miner 2049er (1983) (Micro Fun) [t2] (8 Men).col", "colecovision"],
    ["Miner 2049er (1983) (Micro Fun).col", "colecovision"],
    ["Monkey Academy (1984) (Konami) (Prototype).col", "colecovision"],
    ["Monkey Academy (1984) (Konami).col", "colecovision"],
    ["Montezuma's Revenge (1984) (Parker Bros).col", "colecovision"],
    ["Moonsweeper (1983) (Imagic) [a1].col", "colecovision"],
    ["Moonsweeper (1983) (Imagic).col", "colecovision"],
    ["Motocross Racer (1984) (Xonox) [a1].col", "colecovision"],
    ["Motocross Racer (1984) (Xonox).col", "colecovision"],
    ["Mountain King (1983-84) (Sunrise) [!].col", "colecovision"],
    ["Mountain King (1983-84) (Sunrise) [a1].col", "colecovision"],
    ["Mousetrap (1982) (Exidy).col", "colecovision"],
    ["Mr. Do! (1983) (Universal) [a1].col", "colecovision"],
    ["Mr. Do! (1983) (Universal).col", "colecovision"],
    ["Mr. Do's Castle (1983) (Parker Bros).col", "colecovision"],
    ["Ms. Space Fury (Digital Press) (2001).col", "colecovision"],
    ["Music Vol 1 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Nim by Daniel Bienvenu (Nov 03) (2000) (PD).col", "colecovision"],
    ["Nova Blast (1983) (Imagic) [!].col", "colecovision"],
    ["Nova Blast (1983) (Imagic) [a1][!].col", "colecovision"],
    ["Oil's Well (1984) (Sierravision).col", "colecovision"],
    ["Omega Race (1981-83) (Midway).col", "colecovision"],
    ["One on One Basketball (1984) (Micro Fun).col", "colecovision"],
    ["Pac-Man (1983) (Atarisoft) (Prototype).col", "colecovision"],
    ["Pepper II (1983) (Exidy).col", "colecovision"],
    ["Pere Noel by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Pitfall II - Lost Caverns (1983-84) (Activision).col", "colecovision"],
    ["Pitfall! (1983) (Activision) [!].col", "colecovision"],
    ["Pitstop (1983) (Epyx) [a1].col", "colecovision"],
    ["Pitstop (1983) (Epyx) [a2].col", "colecovision"],
    ["Pitstop (1983) (Epyx).col", "colecovision"],
    ["Popeye (1983) (Parker Bros) [a1].col", "colecovision"],
    ["Popeye (1983) (Parker Bros).col", "colecovision"],
    ["Porky's (1983) (20th Century Fox) (Prototype).col", "colecovision"],
    ["Power Lords - Quest for Volcan (1983) (Prototype).col", "colecovision"],
    ["Puckman Sounds V001 (2003) (PD).col", "colecovision"],
    ["Puckman Sounds V002 (2003) (PD).col", "colecovision"],
    ["Puckman Sounds V003 (2003) (PD).col", "colecovision"],
    ["Purple Dinosaur Massacre by John Dondzila (1996) (PD).col", "colecovision"],
    ["Q-bert (1983) (Parker Bros) [a1].col", "colecovision"],
    ["Q-bert (1983) (Parker Bros).col", "colecovision"],
    ["Q-bert II (1984) (Parker Bros).col", "colecovision"],
    ["Quest for Quintana Roo (1983) (Sunrise) [!].col", "colecovision"],
    ["Quest for Quintana Roo (1983) (Sunrise) [a1].col", "colecovision"],
    ["Reversi Demo by Daniel Bienvenu (2001) (PD).col", "colecovision"],
    ["River Raid (1982-84) (Activision) [!].col", "colecovision"],
    ["Robin Hood (1984) (Xonox) [a1].col", "colecovision"],
    ["Robin Hood (1984) (Xonox).col", "colecovision"],
    ["Roc 'N Rope (1983-84) (Konami).col", "colecovision"],
    ["Rock 'N' Bolt (1984) (Telegames) [a1].col", "colecovision"],
    ["Rock 'N' Bolt (1984) (Telegames).col", "colecovision"],
    ["Rocky Super-Action Boxing (1983) (Coleco).col", "colecovision"],
    ["Rolloverture (1983) (Sunrise).col", "colecovision"],
    ["Sammy Lightfoot (1983) (Sierravision) [a1].col", "colecovision"],
    ["Sammy Lightfoot (1983) (Sierravision).col", "colecovision"],
    ["Sector Alpha (1983) (Spectravideo) [a1].col", "colecovision"],
    ["Sector Alpha (1983) (Spectravideo) [a2].col", "colecovision"],
    ["Sector Alpha (1983) (Spectravideo).col", "colecovision"],
    ["Sewer Sam (1984) (Interphase).col", "colecovision"],
    ["Sir Lancelot (1983) (Xonox) [!].col", "colecovision"],
    ["Skiing (1986) (Telegames).col", "colecovision"],
    ["Slither (1983) (Century II).col", "colecovision"],
    ["Slurpy (1984) (Xonox).col", "colecovision"],
    ["Smurf - Paint 'n Play Workshop (1983).col", "colecovision"],
    ["Smurf - Rescue in Gargamel's Castle (1982).col", "colecovision"],
    ["Sound FX Vol 1 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Sound FX Vol 2 by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Space Fury (1983) (Sega).col", "colecovision"],
    ["Space Invaders Collection Pack Demo (2002) (PD).col", "colecovision"],
    ["Space Invasion Demo by John Dondzila (Feb 06) (1998) (PD).col", "colecovision"],
    ["Space Invasion by John Dondzila (1998) (PD).col", "colecovision"],
    ["Space Panic (1983) (Universal).col", "colecovision"],
    ["Spectank Demo by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Spectron (1983) (Spectravideo).col", "colecovision"],
    ["Spy Hunter (1983-84) (Midway).col", "colecovision"],
    ["Squish 'Em Sam! (1983) (Interphase).col", "colecovision"],
    ["St-Valentine's Day (2002) (PD).col", "colecovision"],
    ["St-Valentine's Day (No Alien Head) (2002) (PD).col", "colecovision"],
    ["Star Fortress by John Dondzila (1997) (PD).col", "colecovision"],
    ["Star Trek - Strategic Operations Simulator (1984) (Sega).col", "colecovision"],
    ["Star Wars - The Arcade Game (1984) (Parker Bros).col", "colecovision"],
    ["Steamroller (1984) (Activision) (Prototype).col", "colecovision"],
    ["Strike It! (1983) (Telegames) [!].col", "colecovision"],
    ["Stubby Demo by Yannick Proulx (2001) (PD) [a1].col", "colecovision"],
    ["Stubby Demo by Yannick Proulx (2001) (PD).col", "colecovision"],
    ["Subroc (1983) (Sega) [a1].col", "colecovision"],
    ["Subroc (1983) (Sega).col", "colecovision"],
    ["Super Action Baseball (1983) (Coleco) [a1].col", "colecovision"],
    ["Super Action Baseball (1983) (Coleco).col", "colecovision"],
    ["Super Action Controller Test Cartridge (1983) (Nuvatec).col", "colecovision"],
    ["Super Action Football (1984) (Coleco) [a1].col", "colecovision"],
    ["Super Action Football (1984) (Coleco).col", "colecovision"],
    ["Super Action Soccer (1984) (Coleco).col", "colecovision"],
    ["Super Cobra (1983) (Parker Bros) [a1].col", "colecovision"],
    ["Super Cobra (1983) (Parker Bros).col", "colecovision"],
    ["Super Cross Force (1983) (Spectravideo) [a1].col", "colecovision"],
    ["Super Cross Force (1983) (Spectravideo).col", "colecovision"],
    ["Super DK! (1983) (Prototype).col", "colecovision"],
    ["Super DK! Junior (1983) (Prototype).col", "colecovision"],
    ["Superpong Demo (2000) (PD).col", "colecovision"],
    ["Tank Wars (1983) (Bit Corp) [!].col", "colecovision"],
    ["Tapper (1984) (Midway).col", "colecovision"],
    ["Tarzan (1984) (Coleco).col", "colecovision"],
    ["Telly Turtle (1984) (Carousel).col", "colecovision"],
    ["Tenchi Muyo Demo by Daniel Bienvenu (2000) (PD).col", "colecovision"],
    ["Threshold (1983) (Sierravision).col", "colecovision"],
    ["Tic Tac Toe by Norman Nithman (1996) (PD) [a1].col", "colecovision"],
    ["Tic Tac Toe by Norman Nithman (1996) (PD).col", "colecovision"],
    ["Time Pilot (1983) (Konami).col", "colecovision"],
    ["Tomarc the Barbarian (1984) (Xonox).col", "colecovision"],
    ["Tournament Tennis (1984) (Imagic) [!].col", "colecovision"],
    ["Tunnels & Trolls Demo (1983) (Adam).col", "colecovision"],
    ["Turbo (1982) (Sega).col", "colecovision"],
    ["Tutankham (1983) (Parker Bros).col", "colecovision"],
    ["Up 'N Down (1984) (Sega).col", "colecovision"],
    ["Venture (1982) (Exidy).col", "colecovision"],
    ["Victory (1983).col", "colecovision"],
    ["Video Hustler (1984) (Konami) (Prototype).col", "colecovision"],
    ["War Games (1983-84).col", "colecovision"],
    ["War Room (1983) (Probe 2000) [a1].col", "colecovision"],
    ["War Room (1983) (Probe 2000).col", "colecovision"],
    ["Wing War (1983) (Imagic).col", "colecovision"],
    ["Winky Trap by John Dondzila (1997) (PD).col", "colecovision"],
    ["Wizard of Id's Wizmath (1984) (Sierravision).col", "colecovision"],
    ["Word Feud (1984) (Xonox).col", "colecovision"],
    ["Yolk's on You, The (1983) (20th Century Fox) (Prototype).col", "colecovision"],
    ["Zaxxon (1982) (Sega).col", "colecovision"],
    ["Zenji (1984) (Activision).col", "colecovision"]
];
